import {
  ArrowLeft,
  ArrowRight,
  Bold,
  Bookmark,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  Clock,
  Code,
  Columns2,
  Copy,
  Cpu,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FilePen,
  FileText,
  Filter,
  Flame,
  Globe,
  Heading2,
  History,
  Image as ImageIcon,
  ImagePlus,
  Inbox,
  Italic,
  KeyRound,
  LayoutTemplate,
  Link,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  LoaderCircle,
  MessageCircle,
  Palette,
  PanelLeft,
  Pause,
  PenLine,
  Play,
  PlugZap,
  Plus,
  QrCode,
  Quote,
  RefreshCw,
  RotateCcw,
  ScanLine,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SquarePen,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  WandSparkles,
  X,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * 图标统一封装（DESIGN.md §4.3：lucide-react 唯一库，业务代码只经 <Icon name>）。
 * 语义名 → lucide 具名导出的映射表；尺寸三档 12（rail 门禁标记等微标注）/ 16（行内）/ 20（按钮内）；
 * 颜色 currentColor、细描边 1.75、aria-hidden（可访问性靠相邻文字/aria-label）。
 */
const ICONS = {
  'pen-line': PenLine,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  shield: Shield,
  clock: Clock,
  'calendar-clock': CalendarClock,
  timer: Timer,
  history: History,
  flame: Flame,
  'message-circle': MessageCircle,
  cpu: Cpu,
  image: ImageIcon,
  'image-plus': ImagePlus,
  globe: Globe,
  send: Send,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  bookmark: Bookmark,
  filter: Filter,
  search: Search,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  sparkles: Sparkles,
  'wand-sparkles': WandSparkles,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'panel-left': PanelLeft,
  'columns-2': Columns2,
  play: Play,
  pause: Pause,
  'trash-2': Trash2,
  x: X,
  copy: Copy,
  'file-text': FileText,
  'file-pen': FilePen,
  'square-pen': SquarePen,
  'list-todo': ListTodo,
  'list-checks': ListChecks,
  'loader-circle': LoaderCircle,
  'circle-alert': CircleAlert,
  'triangle-alert': TriangleAlert,
  check: Check,
  'circle-check': CircleCheck,
  'scan-line': ScanLine,
  smartphone: Smartphone,
  'qr-code': QrCode,
  ellipsis: Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  eye: Eye,
  'eye-off': EyeOff,
  'plug-zap': PlugZap,
  settings: Settings,
  'layout-template': LayoutTemplate,
  palette: Palette,
  'external-link': ExternalLink,
  'link-2': Link2,
  inbox: Inbox,
  bold: Bold,
  italic: Italic,
  list: List,
  'list-ordered': ListOrdered,
  quote: Quote,
  code: Code,
  link: Link,
  'heading-2': Heading2,
  'undo-2': Undo2,
  plus: Plus,
  'key-round': KeyRound,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 16, className }: { name: IconName; size?: 12 | 16 | 20; className?: string }) {
  const Component = ICONS[name];
  return <Component size={size} strokeWidth={1.75} aria-hidden="true" focusable="false" className={className} />;
}
